name: "brasileirao"
version: "1.0.0"
config-version: 2

profile: "brasileirao"

model-paths:  ["models"]
macro-paths:  ["macros"]
test-paths:   ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  brasileirao:
    silver:
      +schema: silver
      +materialized: table
      +tags: ["silver"]
    gold:
      +schema: gold
      +materialized: table
      +tags: ["gold"]
